version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: echo "Deploying..."

  approval_deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Approval for Deployment
          command: echo "Waiting for deployment approval..."

  rollback:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Rollback Application
          command: echo "Rolling back..."

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - approval_deploy:
          type: approval
      - deploy:
          requires:
            - approval_deploy
      - approval_rollback:
          type: approval
          requires:
            - deploy
      - rollback:
          requires:
            - approval_rollback

